<style>
    div.cmbd-upgrade {
        display: inline-block;
        padding: 1em;
        background: #FFF;
        border: solid 1px #E0E0E0;
        max-width: 650px;
        margin: 1em 0;
    }
</style>

<div class="cmbd-upgrade">
    <h3>Want more? Get the PRO</h3>
    <p>Professional version of <?php echo CMBD_NAME; ?> which gives the admin better tools to customize the Business Directory system behavior:
        adding customization options, views, tags, import/export, 3rd party integrations and a lot more.</p>
    <a href="https://www.cminds.com/store/purchase-cm-business-directory-plugin-for-wordpress/" class="button button-primary">Upgrade to PRO</a>
</div>